name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpwd
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3

      # Backend Tests
      - name: Setup Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install backend deps
        run: |
          cd backend
          yarn install --frozen-lockfile
      - name: Run backend tests
        run: |
          cd backend
          yarn test
        env:
          DB_HOST: 127.0.0.1
          DB_USER: user
          DB_PASS: password
          DB_NAME: ecommerce
          JWT_SECRET: testsecret

      # Frontend Tests
      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install frontend deps
        run: |
          cd frontend
          yarn install --frozen-lockfile
      - name: Run frontend tests
        run: |
          cd frontend
          yarn test --ci